
# http://localhost:3000/api/v1/users/xtreme

# http://localhost:3000/api/v1/xtreme

# delete http://localhost:3000/api/v1/xtreme/xxix

# POST http://localhost:3000/api/v1/xtreme/xxx HTTP/1.1
# content-type: application/json

GET https://www.sokkercuba.com/api/v1/xtreme/xxx

# POST https://www.sokkercuba.com/api/v1/xtreme/xxxii HTTP/1.1
# content-type: application/json

