export const skillsLevels = {
  0: "Tragic",
  1: "Hopeless",
  2: "Unsatisfactory",
  3: "Poor",
  4: "Weak",
  5: "Average",
  6: "Adequate",
  7: "Good",
  8: "Solid",
  9: "Very Good",
  10: "Excellent",
  11: "Formidable",
  12: "Outstanding",
  13: "Incredible",
  14: "Brilliant",
  15: "Magical",
  16: "Unearthly",
  17: "Divine",
  18: "Superdivine",
};
